### ISSUE TITLE
I want to document

### ISSUE THREAD

**Issue by esengine** [lucas-miranda/Raccoon#1]
I hope to have a document that will give you a detailed description of what you have now. It's best to give a simple example. I am looking forward to your framework

**Comment by lucas-miranda** [comment]
Sorry for the long time to answer
but of course, feel free to document anything you want to, it will be very nice 😄 

I just documented [**Scene.cs**](https://github.com/lucas-miranda/Raccoon/blob/master/Raccoon/Core/Scene.cs) completely, but it can be improved too

and you can use the framework already, if you want. It's working fine and if something goes wrong, feel free to open an issue and I'll look into it!
